# clusterProfiler ORA / hypergeometric tests used for figure panels
#
# This script records the clusterProfiler::enricher() calls used for the
# Hallmark over-representation analyses. It starts from prepared gene vectors
# and expression universes generated by the upstream CUT&RUN/RNA-seq and
# HiChIP integration analyses.
# Functions return standardized tables suitable for public figure scripts.

suppressPackageStartupMessages({
  library(clusterProfiler)
  library(dplyr)
  library(msigdbr)
  library(purrr)
  library(qs)
  library(readr)
  library(stringr)
  library(tibble)
})

project_dir <- Sys.getenv("PROJECT_DIR", unset = normalizePath(".", mustWork = FALSE))
output_dir <- file.path(Sys.getenv("FIGURES_OUTPUT_DIR", file.path(project_dir, "code_availability", "Figures", "output")), "clusterProfiler_ORA")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

h_gene_sets <- msigdbr(species = "Homo sapiens", category = "H") %>%
  dplyr::select(gs_name, gene_symbol)

as_ora_tbl <- function(enrich_result, group, cell_line = NA_character_, treatment = NA_character_) {
  as_tibble(enrich_result@result) %>%
    mutate(
      group = group,
      group_cellline = cell_line,
      group_treatment = treatment,
      GeneRatio_number = map_dbl(str_split(GeneRatio, "/"), ~ as.numeric(.x[1]) / as.numeric(.x[2]))
    )
}

# Central Hallmark ORA wrapper; use an expression universe when supplied.
run_hallmark_ora <- function(genes, universe = NULL) {
  clusterProfiler::enricher(
    gene = unique(na.omit(genes)),
    TERM2GENE = h_gene_sets,
    pvalueCutoff = 1,
    qvalueCutoff = 1,
    universe = universe
  )
}

# RB-up non-promoter peaks linked to RNA-seq up/down genes.
# Original source:
# analysis_paper/02_RB_nonprom_function/02_RBup_geneexprsup_hypergeometric
run_rb_peak_expression_ora <- function(combined_df, exprs_df) {
  genes_up <- combined_df %>%
    filter(
      peaks_exprs_group == "paired",
      annotation_promoter_peaks == "Other",
      logFC_MLE_exprs > 0,
      padj_exprs < 0.05
    ) %>%
    pull(X.genesymb_exprs) %>%
    unique()

  genes_down <- combined_df %>%
    filter(
      peaks_exprs_group == "paired",
      annotation_promoter_peaks == "Other",
      logFC_MLE_exprs < 0,
      padj_exprs < 0.05
    ) %>%
    pull(X.genesymb_exprs) %>%
    unique()

  bind_rows(
    as_ora_tbl(
      run_hallmark_ora(genes_up, universe = exprs_df$SYMBOL),
      group = "RBup_exprsup_nonprom_hypergeo"
    ),
    as_ora_tbl(
      run_hallmark_ora(genes_down, universe = exprs_df$SYMBOL),
      group = "RBup_exprsdown_nonprom_hypergeo"
    )
  )
}

# Same ORA structure for multiple cell line/treatment lists.
# Original source:
# analysis/CutRun/241217_MCF7_ZR751_Parent_sgRB_palbo_RB_CnR/R_analysis/5.RBup_geneexprs_hypergeo
run_rb_peak_expression_ora_list <- function(genes_up, genes_down, exprs_df, treatment = "PB") {
  up_tbl <- imap(genes_up, function(genes_i, nm) {
    as_ora_tbl(
      run_hallmark_ora(genes_i, universe = exprs_df[[nm]]$SYMBOL),
      group = "RBup_exprsup_nonprom_hypergeo",
      cell_line = nm,
      treatment = treatment
    )
  })

  down_tbl <- imap(genes_down, function(genes_i, nm) {
    as_ora_tbl(
      run_hallmark_ora(genes_i, universe = exprs_df[[nm]]$SYMBOL),
      group = "RBup_exprsdown_nonprom_hypergeo",
      cell_line = nm,
      treatment = treatment
    )
  })

  bind_rows(up_tbl, down_tbl)
}

# HiChIP loop-connected gene sets. These analyses used the default universe in
# clusterProfiler::enricher(), matching the original notebooks.
# Original source:
# analysis_paper/02_RB_nonprom_function/04_RBup_HiChIP_H3K27ac_hypergeometric
run_hichip_loop_ora <- function(genes_list) {
  imap(genes_list, function(genes_i, nm) {
    as_ora_tbl(run_hallmark_ora(genes_i), group = nm)
  }) %>%
    bind_rows()
}

# Overlap of nearby genes from MCF7 and ZR751 RB-up non-promoter peaks.
# Original source:
# analysis/answerToReviewer/reviewer3/02_RBnonprom_uppeaks_nearbygenes_MCF7ZR751overlap/ORA_genes_figure2a.Rmd
run_overlap_gene_ora <- function(gene_sets) {
  overlap_genes <- intersect(gene_sets$MCF7, gene_sets$ZR751)
  as_ora_tbl(run_hallmark_ora(overlap_genes), group = "MCF7_ZR751_overlap")
}

if (sys.nframe() == 0) {
  message("This file defines the clusterProfiler::enricher() ORA calls used by the paper analyses.")
  message("Load prepared gene-list objects, then call run_rb_peak_expression_ora(), run_rb_peak_expression_ora_list(), run_hichip_loop_ora(), or run_overlap_gene_ora().")
}
